# Generated by Django 4.2.5 on 2023-09-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="servicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titulo")),
                (
                    "subtitle",
                    models.CharField(max_length=200, verbose_name="subtitulo"),
                ),
                ("content", models.TextField(max_length=200, verbose_name="contenido")),
                (
                    "image",
                    models.ImageField(upload_to="services", verbose_name="imagen"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "update",
                    models.DateTimeField(auto_now=True, verbose_name="cambiado"),
                ),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ["-created"],
            },
        ),
    ]
