# Generated by Django 4.2.5 on 2023-09-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicio", "0002_alter_servicios_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicios",
            name="image",
            field=models.ImageField(upload_to="servicio", verbose_name="imagen"),
        ),
    ]
