# Generated by Django 4.2.5 on 2023-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicio", "0004_rename_image_servicios_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicios",
            name="precios",
            field=models.IntegerField(default=1, max_length=200, verbose_name="precio"),
            preserve_default=False,
        ),
    ]
