# Generated by Django 4.2.5 on 2023-09-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicio", "0006_alter_servicios_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicios",
            name="images",
            field=models.ImageField(upload_to="servicios", verbose_name="images"),
        ),
    ]
